import { ReaderConfig } from "./navigator/IFrameNavigator";
import { Locator } from "./model/Locator";
export declare const IS_DEV = true;
export declare function unload(): Promise<void>;
export declare function hasMediaOverlays(): boolean;
export declare function startReadAloud(): void;
export declare function stopReadAloud(): void;
export declare function pauseReadAloud(): void;
export declare function resumeReadAloud(): void;
export declare function saveBookmark(): Promise<any>;
export declare function deleteBookmark(bookmark: any): Promise<any>;
export declare function deleteAnnotation(highlight: any): Promise<any>;
export declare function addAnnotation(highlight: any): Promise<any>;
export declare function tableOfContents(): Promise<any>;
export declare function readingOrder(): Promise<any>;
export declare function bookmarks(): Promise<any>;
export declare function annotations(): Promise<any>;
export declare function search(term: any, current: any): Promise<any>;
export declare function goToSearchIndex(href: any, index: any, current: any): Promise<void>;
export declare function goToSearchID(href: any, index: any, current: any): Promise<void>;
export declare function clearSearch(): Promise<void>;
export declare function currentResource(): number;
export declare function mostRecentNavigatedTocItem(): string;
export declare function totalResources(): number;
export declare function publicationLanguage(): string[];
export declare function resetUserSettings(): Promise<void>;
export declare function applyUserSettings(userSettings: any): Promise<void>;
export declare function currentSettings(): Promise<{
    appearance: string;
    fontFamily: string;
    textAlignment: string;
    columnCount: string;
    verticalScroll: boolean;
    fontSize: number;
    wordSpacing: number;
    letterSpacing: number;
    pageMargins: number;
    lineHeight: number;
}>;
export declare function increase(incremental: any): Promise<void>;
export declare function decrease(incremental: any): Promise<void>;
export declare function resetTTSSettings(): Promise<void>;
export declare function applyTTSSettings(ttsSettings: any): Promise<void>;
export declare function applyTTSSetting(key: any, value: any): Promise<void>;
export declare function applyPreferredVoice(value: any): Promise<void>;
export declare function resetMediaOverlaySettings(): Promise<void>;
export declare function applyMediaOverlaySettings(setting: any): Promise<void>;
export declare function goTo(locator: any): void;
export declare function nextResource(): void;
export declare function previousResource(): void;
export declare function nextPage(): void;
export declare function previousPage(): void;
export declare function atStart(): boolean;
export declare function atEnd(): boolean;
export declare function scroll(value: any): Promise<void>;
export declare function currentLocator(): Locator;
export declare function positions(): any;
export declare function goToPosition(value: any): void;
export declare function applyAttributes(value: any): void;
export declare function snapToElement(value: any): void;
export declare function load(config: ReaderConfig): Promise<any>;
